//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process
    {
        public Process()
        {
            this.AssignedTo = new HashSet<User>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime DueDate { get; set; }
    
        public virtual User CreatedBy { get; set; }
        public virtual ICollection<User> AssignedTo { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual Stream Stream { get; set; }
    }
}
