//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stream
    {
        public Stream()
        {
            this.AssignedTo = new HashSet<User>();
            this.Tasks = new HashSet<Task>();
            this.Processes = new HashSet<Process>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<User> AssignedTo { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Process> Processes { get; set; }
    }
}
