//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.AssignedTo = new HashSet<User>();
            this.Tags = new HashSet<Tag>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string DueDate { get; set; }
    
        public virtual ICollection<User> AssignedTo { get; set; }
        public virtual User CreatedBy { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual Process Process { get; set; }
        public virtual Stream Stream { get; set; }
        public virtual TaskStatusType TaskStatus { get; set; }
    }
}
