//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserGroups = new HashSet<UserGroup>();
            this.Streams = new HashSet<Stream>();
            this.CreatedProcesses = new HashSet<Process>();
            this.Tasks = new HashSet<Task>();
            this.CreatedTasks = new HashSet<Task>();
            this.Processes = new HashSet<Process>();
            this.Timesheets = new HashSet<Timesheet>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string LastLoginDate { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<UserGroup> UserGroups { get; set; }
        public virtual ICollection<Stream> Streams { get; set; }
        public virtual ICollection<Process> CreatedProcesses { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Task> CreatedTasks { get; set; }
        public virtual ICollection<Process> Processes { get; set; }
        public virtual ICollection<Timesheet> Timesheets { get; set; }
    }
}
