//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetails : User
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PersonalId { get; set; }
        public string Address { get; set; }
        public string AddressExtra { get; set; }
        public string PhoneNumber { get; set; }
        public string IM { get; set; }
        public string CellPhoneNumber { get; set; }
        public string Website { get; set; }
    }
}
